<?php

namespace App\Repository;

use App\Utils\Page;
use App\Utils\Pageable;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPage(Pageable $pageable) : Page{
        return new Page($this->createQueryBuilder('l')->orderBy('l.id', 'DESC'), $pageable);
    }
}
