<?php

namespace App\Repository;

/**
 * PasswordRecoveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordRecoveryRepository extends \Doctrine\ORM\EntityRepository
{
}
