<?php

namespace App\Repository;

use App\Entity\ProductCategory;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByName(string $name): ?ProductCategory
    {
        return $this->createQueryBuilder('c')
            ->where('c.categoryName = :catName')
            ->orWhere('c.latinName = :catName')
            ->setParameter('catName', $name)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
