<?php

namespace App\Repository;

use App\Utils\Page;
use App\Utils\Pageable;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPage(Pageable $pageable) : Page{
        return new Page($this->createQueryBuilder('q')->orderBy('q.date', 'DESC'), $pageable);
    }
}
