1:
    icon: fa-shopping-cart
    title: 'Лесни за Употреба~!'
    body: 'За всяка домакиня и всеки дом. Опростения начин за работа ги прави удобни и приятни за приготвяне на домашно консервирана храна.'
2:
    icon: fa-pie-chart
    title: Качество
    body: 'Изработени са от качествени материали и гарантират плътно и сигурно затваряне на кутиите.'
3:
    icon: fa-handshake-o
    title: Лоялност
    body: 'Всички модели имат една година гаранция и следгаранционен сервиз.'
