aboutUs: 'The company "Kolev & Co LTD" is specialized in creating can sealing machines for different kinds of cans as well as providing the required gear for the different can sizes and types. We can answer every technical question.'
address: 'Residential: Mladost-2, Yordan Radichkov 16'
location: 'Montana, Bulgaria'
