aboutUs: 'Фирма "Колев и Ко ООД" е специализирана в производството на машини за затваряне на различни видове консервни кутии, както и на нужната екипировка за различните размери и видове. Можем да отговорим на всяко техническо задание.'
address: 'ЖК: Младост-2, Поп Пунчо 6'
location: 'Монтана, България'
